Implementation of authorization
vg-22/frontend_globa pull request #3
Opened 2022-07-11 09:27 UTC by vg-22

Created authorization and registration

2022-07-11 09:58 UTC, altitovsky requested changes
и удали картинки из репозитория

2022-07-11 09:58 UTC, altitovsky commented on src/api/index.js
> +  baseURL: `${process.env.REACT_APP_BASE_URL}/api`,
почему бы /api не вынести в env?

2022-07-11 09:58 UTC, altitovsky commented on src/components/AuthModal/index.jsx
> +import { memo, useState } from 'react';
ты же уже импортировала реакт

2022-07-11 09:58 UTC, altitovsky commented on src/components/Header/index.jsx
> +import { useSelector, useDispatch } from 'react-redux';
импорты нужно разделять

2022-07-11 09:58 UTC, altitovsky commented on src/components/Main/index.jsx
> +    <NewsCard title={title} key={id} text={text} />
кидай в NewsCard объект новости, а не поля по отдельности

2022-07-11 09:58 UTC, altitovsky commented on src/components/NewsCard/index.jsx
> +NewsCard.defaultProps = {
зачем дефолтные пропсы? Лучше в propTypes задавай isRequired

2022-07-11 09:58 UTC, altitovsky commented on src/redux/reducers/auth.js
> +import { getToken } from '../../helpers/localStorage';
зачем тут getToken? редьюсер - чистая функция, не должно быть никаких сайд эффектов

2022-07-11 09:58 UTC, altitovsky commented on src/redux/reducers/news.js
> +        error: action.error,
если произошла ошибка, она останется в стэйте навсегда?

2022-07-12 08:47 UTC, altitovsky requested changes

2022-07-12 08:47 UTC, altitovsky commented on src/redux/sagas/loginSaga.js
> +    Boolean(getToken());
и зачем это тут?

2022-07-12 11:34 UTC, iPetrovDunice requested changes

2022-07-12 11:34 UTC, iPetrovDunice commented on src/components/Main/index.jsx
> +  const { news } = useSelector(((item) => item.newsReducer));
вместо item нужно писать state, ты же со стейтом работаешь

2022-07-12 11:34 UTC, iPetrovDunice commented on src/redux/reducers/auth.js
> +  isAccess: Boolean(getToken()),
Зачем нужна данная переменная? У на есть loginUser, он либо есть, либо null, токен может быть внутри localStorage, но он может быть не валидный, а юзер не может быть заполнен, если токен не валидный

2022-07-12 11:34 UTC, iPetrovDunice commented on src/redux/reducers/auth.js
> +        loginUser: action.payload,
loginUser заполняется на этапе REQUESTED, или на этапе SUCCESS? почему дважды заполняется?

2022-07-12 11:34 UTC, iPetrovDunice commented on src/redux/reducers/auth.js
> +        error: null,
Когда юзер выходит - loginUser остается с данными о юзере?

2022-07-12 11:34 UTC, iPetrovDunice commented on src/redux/reducers/auth.js
> +import { getToken } from '../../helpers/localStorage';
токен тут не нужен

2022-07-13 05:57 UTC, merged